
version: '3.8'
services:
  thinking-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thinking-mcp-server
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - MCP_API_KEY=mcp-api-key-2025-super-secure-token
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3